### ISSUE TITLE
Regression from 1.0.2 to 1.1.0

### ISSUE THREAD

**Issue by Robloche** [sandflow/imscJS#169]
Since I updated to version 1.1.0, I get a systematic crash trying to render my subtitles.
Here's an [example](https://drive.google.com/file/d/1JzFcT1cJUARsRVt_2D8gltcTlEIMJPqC/view?usp=sharing).

I tried to pin down the culprit and reached this part of code (in `html.js`):
![image](https://user-images.githubusercontent.com/10497009/67011574-2e3bd080-f0f0-11e9-806f-ff2af79a2099.png)

At this point, `attr` seems to be of an incorrect type and, of course, that leads to the following:
![image](https://user-images.githubusercontent.com/10497009/67011890-b28e5380-f0f0-11e9-8485-7c68f43e1eec.png)

**Comment by palemieux** [comment]
@Robloche Yes, imscJS should not die. However the document is also not a valid IMSC document: `px` units are used, e.g. at `tts:fontSize="22px"`, but the root container extent is not specified in `px` -- see https://www.w3.org/TR/ttml-imsc1.1/#extent-root.

**Comment by palemieux** [comment]
@Robloche Should be fixed at #170

**Comment by Robloche** [comment]
I'm not the one producing the TTMLs I use... So it's perfect if your lib can handle badly formed files.

Thanks!

**Comment by Robloche** [comment]
I updated to 1.1.1 and still get the same error.
I understand the file I'm parsing is not valid but I thought version 1.1.1 would handle it anyway.
Am I mistaken?

**Comment by palemieux** [comment]
@Robloche Do you still see an uncaught exception?

**Comment by Robloche** [comment]
Yes, precisely.

**Comment by palemieux** [comment]
@Robloche I cannot replicate it at https://www.sandflow.com/imsc1_1/index.html using the file you provided above. Can you confirm you are using 1.1.1-rc.1?

**Comment by Robloche** [comment]
With 1.1.1-rc.1, the uncaught exceptions are gone. Thanks!

But my subtitles are all messed up:
![image](https://user-images.githubusercontent.com/10497009/67504508-cd7d3c80-f689-11e9-8afc-0928a6f5c405.png)

**Comment by palemieux** [comment]
The document specifies `tts:fontSize="22px"`. Since the author did not specify a root extent in pixels, it is not possible to determine what font size the author actually wanted, e.g. is it `22px` relative to a `1080px` or `720px` or `480px` tall image? Also the region height is set to `10%`, which results in much clipping.

Can you DM me at pal@sandflow.com the source of file? It would be good to address the fundamental issue.

**Comment by Robloche** [comment]
I tried to change the font size on-the-fly, by replacing `22px` by a percentage but I still get the clipped vertical text.

Also, I DMed you a file.

**Comment by palemieux** [comment]
@Robloche My guess is that the document was authored against 720p video. Adding the `tts:extent="1280px 720px"` attribute to the `tt` element seems to result in something usable.

**Comment by Robloche** [comment]
I tried adding `tts:extent="1280px 720px"` to `tt` and now have this:
```
<tt xml:lang="fr" xmlns="http://www.w3.org/ns/ttml" xmlns:tts="http://www.w3.org/ns/ttml#styling" tts:extent="1280px 720px">
	<head>
		<metadata xmlns:ttm="http://www.w3.org/ns/ttml#metadata">
			<ttm:title>17378_16070_pigedecristal_hd</ttm:title>
			<ttm:desc>Converted by the Online Subtitle Converter developed by J. David Requejo - modified for diacritic support
			</ttm:desc>
		</metadata>
		<styling>
		 <style tts:displayAlign="center" tts:backgroundColor="transparent" tts:extent="100% 10%" tts:origin="0% 89%" tts:textAlign="center" tts:fontSize="22px" tts:fontFamily="proportionalSansSerif" xml:id="backgroundStyle"/>
		<style tts:backgroundColor="transparent" xml:id="speakerStyle" tts:textOutline="black 1px 0px" tts:color="white" style="backgroundStyle"/>
		</styling>
		<layout><region xml:id="region1" style="speakerStyle" /></layout>
	</head>
    ...
```

But i get the same result: clipped vertical text.

**Comment by palemieux** [comment]
@Robloche Here's what I get:

![Annotation 2019-10-29 082340](https://user-images.githubusercontent.com/4871350/67782034-7ed2f800-fa25-11e9-8bf6-de4ccf63bc37.png)

Do you see something different?

**Comment by Robloche** [comment]
And here's what _I_ get:
![image](https://user-images.githubusercontent.com/10497009/67950553-184b0700-fbea-11e9-9fb2-8d74c111afaf.png)

I inspected the DOM and saw this:
![image](https://user-images.githubusercontent.com/10497009/67950631-403a6a80-fbea-11e9-9ed6-7fa638cef5f3.png)

I don't know what's causing all these `<SPAN>`: my code or your lib?

**Comment by palemieux** [comment]
@Robloche The library unfortunately needs to wrap spans and use the `getBoundingClientRect()`(https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) API call to detect line breaks, in order to polyfill subtitle/caption features not supported by web browsers. Are you using the library in a full web browser, or in a node.js environment, or something else? Also, is the containing `div` already in the DOM when calling imscJS?

**Comment by Robloche** [comment]
I'm back again. :o)

So, I cleaned up some old CSS and got rid of my vertical stack of `SPAN`s.
But I had to give a `min-width` to these `SPAN`s because the empty ones were simply being collapsed into 0-width element...

Did I miss something again?
